<a href="https://colab.research.google.com/github/NiuwenC/google-tensorflow/blob/main/mnist_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])




11493376/11490434 [==============================] - 0s 0us/step


In [2]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.23814395, -0.34884673, -0.5993761 ,  0.6814533 , -0.7688085 ,
         0.20864195, -0.23290697,  0.10692714,  0.04670875, -0.1102995 ]],
      dtype=float32)

In [3]:
tf.nn.softmax(predictions).numpy()

array([[0.12632921, 0.07023878, 0.05467306, 0.19680248, 0.04615193,
        0.12265668, 0.07887311, 0.11079421, 0.10431927, 0.08916136]],
      dtype=float32)

In [4]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [5]:
loss_fn(y_train[:1], predictions).numpy()

2.098366

In [6]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.4834 - accuracy: 0.8586
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1483 - accuracy: 0.9560
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1082 - accuracy: 0.9662
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0872 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0727 - accuracy: 0.9766


In [7]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0702 - accuracy: 0.9796


[0.0701650008559227, 0.9796000123023987]

In [8]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [9]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.0593310e-08, 2.4206048e-10, 6.5693879e-05, 2.5943064e-04,
        1.0751945e-10, 1.7684773e-07, 1.5010973e-13, 9.9966502e-01,
        3.4929701e-07, 9.3431954e-06],
       [6.5785642e-08, 6.4951664e-06, 9.9996662e-01, 1.3483747e-05,
        2.5417416e-14, 9.3294807e-07, 3.2340921e-07, 9.8741334e-14,
        1.2037370e-05, 2.1526351e-14],
       [2.1423038e-07, 9.9941051e-01, 1.7986831e-04, 6.0365060e-06,
        2.0972748e-05, 1.4491291e-06, 5.5900532e-06, 3.3598315e-04,
        3.9135233e-05, 3.0240125e-07],
       [9.9994063e-01, 5.0072054e-11, 5.7786692e-05, 5.2092775e-09,
        2.8504987e-09, 2.5088744e-07, 5.3194378e-07, 6.0680293e-07,
        1.3286121e-09, 2.5816291e-07],
       [1.7134497e-06, 1.1695442e-09, 2.8970471e-05, 2.1370796e-07,
        9.9569917e-01, 1.6212688e-06, 1.5332571e-06, 2.9154895e-05,
        3.1410582e-05, 4.2063165e-03]], dtype=float32)>